module.exports = {
  PORT: process.env.PORT || 5000,
  NODE_ENV: process.env.NODE_ENV || "development",
  DB_USER: process.env.DB_USER || "postgres",
  DB_PASSWORD: process.env.DB_PASSWORD || "postgres",
  DB_PORT: process.env.DB_PORT || 5432,
  DB_NAME: process.env.DB_NAME || "eportfolio",
  DB_HOST: process.env.DB_HOST || "localhost",
  DB_DIALECT: process.env.DB_DIALECT || "postgres",
  NODE_ENV: process.env.NODE_ENV || "development",
  JWT_SECRET: process.env.JWT_SECRET || "changeme",
  ACCESS_EXPIRES: process.env.ACCESS_EXPIRES || "15m",
  REFRESH_EXPIRES: process.env.REFRESH_EXPIRES || "7d",
  REFRESH_TOKEN_SECRET: process.env.REFRESH_TOKEN_SECRET || "changeme",
  CORS_WHITELIST: process.env.CORS_WHITELIST || "",
  ACCESS_TOKEN_SECRET: process.env.ACCESS_TOKEN_SECRET,
};
